### ISSUE TITLE
Inital zoom

### ISSUE THREAD

**Issue by joachimwolff** [pkerpedjiev/fornac#5]
The inital zoom should be less. For example if you just put the structure (..) into forna the zoom so massive that the for nodes fill out the container completely. Furthermore, only 2/3 of a node is visible.
See: http://rna.informatik.uni-freiburg.de/trunk/AntaRNA/Input.jsp and put (..) into the structure constraint field.

**Comment by pkerpedjiev** [comment]
Holy crap. Sorry for the late reply. I just saw this issue and it should be fixed in the latest `develop` branch. Just set `maxNodeRadius` in the FornaContainer constructor options to indicate how large you want to allow nodes to get initially or when centered.

In the future, if I don't reply within a week, please ping me again.
